
import hib.dto.NewsTable;
import hib.dto.QueryTable;
import hib.dto.StudentTable;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.hibernate.criterion.Restrictions;
import org.jdatepicker.DateModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Achint Rawal
 */
public class HomePageStudents extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    CardLayout cl;
    public HomePageStudents() 
    {
        initComponents();
        cl = (CardLayout)BG.getLayout();
        Home.setBackground(new Color(85,65,118));
        homeLabel3.setText("Welcome, "+SignIn.id);
        
        SessionFactory sf=new Configuration().configure().buildSessionFactory();
        Session session=sf.openSession();
        Transaction tx=session.beginTransaction();
        Criteria crit = session.createCriteria(QueryTable.class);
        crit.add(Restrictions.eq("stuName",SignIn.id));
        List<QueryTable> data=crit.list();
        DefaultTableModel dtm= (DefaultTableModel)jTable1.getModel();
        for(QueryTable st:data)
        {
            Object obj[]={st.getFaName(),st.getQuery(),st.getRequestDate(),st.getTo(),st.getFrom()};
            dtm.addRow(obj);
        }
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm");  
        LocalDateTime now = LocalDateTime.now();  
        homeLabel1.setText("Login Time : "+dtf.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Footer = new javax.swing.JPanel();
        contactD = new javax.swing.JLabel();
        contactD1 = new javax.swing.JLabel();
        LeftSide = new javax.swing.JPanel();
        Settings = new javax.swing.JPanel();
        settingLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Query = new javax.swing.JPanel();
        queryLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Update = new javax.swing.JPanel();
        updateLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LOGO = new javax.swing.JLabel();
        BG = new javax.swing.JPanel();
        HomeC = new javax.swing.JPanel();
        TopBar = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        homeLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        homeLabel3 = new javax.swing.JLabel();
        homeLabel1 = new javax.swing.JLabel();
        QueryC = new javax.swing.JPanel();
        inbox = new javax.swing.JPanel();
        inboxT = new javax.swing.JLabel();
        inboxicon = new javax.swing.JLabel();
        Inboxbtn = new javax.swing.JPanel();
        inboxBtnTxt = new javax.swing.JLabel();
        newQuery = new javax.swing.JPanel();
        queryT = new javax.swing.JLabel();
        queryIcon = new javax.swing.JLabel();
        NewQueryBtn = new javax.swing.JPanel();
        inboxBtnTxt1 = new javax.swing.JLabel();
        TopBar2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        UpdateC = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        SettingC = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        NewQueryC = new javax.swing.JPanel();
        BackNewQuery = new javax.swing.JLabel();
        Student2 = new javax.swing.JPanel();
        StudentT2 = new javax.swing.JLabel();
        AddNeQuery = new javax.swing.JPanel();
        SignInBtnTxt2 = new javax.swing.JLabel();
        StuID = new javax.swing.JLabel();
        StuPW = new javax.swing.JLabel();
        FaName = new javax.swing.JTextField();
        StuID1 = new javax.swing.JLabel();
        NQuery = new javax.swing.JTextField();
        StuID2 = new javax.swing.JLabel();
        jDatePicker1 = new org.jdatepicker.JDatePicker();
        jDatePicker2 = new org.jdatepicker.JDatePicker();
        InboxC = new javax.swing.JPanel();
        BackInbox = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        PasswordResetC = new javax.swing.JPanel();
        BackPasswordReset = new javax.swing.JLabel();
        inbox1 = new javax.swing.JPanel();
        inboxT1 = new javax.swing.JLabel();
        Inboxbtn1 = new javax.swing.JPanel();
        inboxBtnTxt2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CNewPassword = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        oldPassword = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        newPassword = new javax.swing.JPasswordField();
        InvalidPWD = new javax.swing.JLabel();
        InvalidPWD1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Footer.setBackground(new java.awt.Color(122, 79, 222));
        Footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contactD.setBackground(new java.awt.Color(255, 255, 255));
        contactD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        contactD.setForeground(new java.awt.Color(255, 255, 255));
        contactD.setText("Contact Number : +91 1234567890");
        Footer.add(contactD, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 290, 30));

        contactD1.setBackground(new java.awt.Color(255, 255, 255));
        contactD1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        contactD1.setForeground(new java.awt.Color(255, 255, 255));
        contactD1.setText("Email Id : lecturebackup@collegename.in");
        Footer.add(contactD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 330, 30));

        getContentPane().add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1210, 50));

        LeftSide.setBackground(new java.awt.Color(53, 33, 89));
        LeftSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Settings.setBackground(new java.awt.Color(64, 43, 100));
        Settings.setPreferredSize(new java.awt.Dimension(500, 300));
        Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsMouseClicked(evt);
            }
        });
        Settings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settingLabel.setBackground(new java.awt.Color(255, 255, 255));
        settingLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        settingLabel.setForeground(new java.awt.Color(255, 255, 255));
        settingLabel.setText("Settings");
        Settings.add(settingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings.png"))); // NOI18N
        Settings.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 50));

        LeftSide.add(Settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 310, 50));

        Home.setBackground(new java.awt.Color(64, 43, 100));
        Home.setPreferredSize(new java.awt.Dimension(500, 300));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeLabel.setBackground(new java.awt.Color(255, 255, 255));
        homeLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel.setText(" Home");
        Home.add(homeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 210, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        Home.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 50));

        LeftSide.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 310, 50));

        Query.setBackground(new java.awt.Color(64, 43, 100));
        Query.setPreferredSize(new java.awt.Dimension(500, 300));
        Query.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QueryMouseClicked(evt);
            }
        });
        Query.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        queryLabel.setBackground(new java.awt.Color(255, 255, 255));
        queryLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        queryLabel.setForeground(new java.awt.Color(255, 255, 255));
        queryLabel.setText("Query");
        Query.add(queryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 210, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/query.png"))); // NOI18N
        Query.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 50));

        LeftSide.add(Query, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 310, 50));

        Update.setBackground(new java.awt.Color(64, 43, 100));
        Update.setPreferredSize(new java.awt.Dimension(500, 300));
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
        });
        Update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateLabel.setBackground(new java.awt.Color(255, 255, 255));
        updateLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        updateLabel.setForeground(new java.awt.Color(255, 255, 255));
        updateLabel.setText("Updates");
        Update.add(updateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 210, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        Update.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 50));

        LeftSide.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 310, 50));

        LOGO.setBackground(new java.awt.Color(255, 255, 255));
        LOGO.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LOGO.setForeground(new java.awt.Color(255, 255, 255));
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo1.png"))); // NOI18N
        LeftSide.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 180, 100));

        getContentPane().add(LeftSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 640));

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setLayout(new java.awt.CardLayout());

        HomeC.setBackground(new java.awt.Color(255, 255, 255));
        HomeC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopBar.setBackground(new java.awt.Color(122, 79, 222));
        TopBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TopBar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Acropolis Institute Of Technology And Research");
        TopBar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 550, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aitr.png"))); // NOI18N
        TopBar.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        HomeC.add(TopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 130));

        homeLabel2.setBackground(new java.awt.Color(0, 0, 0));
        homeLabel2.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        homeLabel2.setText("History,");
        HomeC.add(homeLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 210, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Faculty Name", "Query", "Request Date", "To Date", "From Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        HomeC.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 830, 110));

        homeLabel3.setBackground(new java.awt.Color(255, 255, 255));
        homeLabel3.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        homeLabel3.setText("Welcome, ");
        HomeC.add(homeLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 210, 30));

        homeLabel1.setBackground(new java.awt.Color(255, 255, 255));
        homeLabel1.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        homeLabel1.setText("Login Time : ");
        HomeC.add(homeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 340, 30));

        BG.add(HomeC, "card2");

        QueryC.setBackground(new java.awt.Color(255, 255, 255));
        QueryC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inbox.setBackground(new java.awt.Color(255, 255, 255));
        inbox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        inbox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inboxT.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        inboxT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inboxT.setText("Inbox");
        inboxT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        inbox.add(inboxT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 60));

        inboxicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inboxicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inbox1.png"))); // NOI18N
        inboxicon.setToolTipText("");
        inbox.add(inboxicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 290, 60));

        Inboxbtn.setBackground(new java.awt.Color(64, 43, 100));
        Inboxbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InboxbtnMouseClicked(evt);
            }
        });
        Inboxbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inboxBtnTxt.setBackground(new java.awt.Color(255, 255, 255));
        inboxBtnTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        inboxBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        inboxBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inboxBtnTxt.setText("Open Inbox");
        Inboxbtn.add(inboxBtnTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 160, 40));

        inbox.add(Inboxbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 240, 40));

        QueryC.add(inbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 290, 370));

        newQuery.setBackground(new java.awt.Color(255, 255, 255));
        newQuery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        newQuery.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        queryT.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        queryT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        queryT.setText("New Query");
        queryT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        newQuery.add(queryT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 60));

        queryIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        queryIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newQuery1_1.png"))); // NOI18N
        queryIcon.setToolTipText("");
        newQuery.add(queryIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 290, 70));

        NewQueryBtn.setBackground(new java.awt.Color(64, 43, 100));
        NewQueryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewQueryBtnMouseClicked(evt);
            }
        });
        NewQueryBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inboxBtnTxt1.setBackground(new java.awt.Color(255, 255, 255));
        inboxBtnTxt1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        inboxBtnTxt1.setForeground(new java.awt.Color(255, 255, 255));
        inboxBtnTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inboxBtnTxt1.setText("Add New Query");
        NewQueryBtn.add(inboxBtnTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 180, 40));

        newQuery.add(NewQueryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 240, 40));

        QueryC.add(newQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 290, 370));

        TopBar2.setBackground(new java.awt.Color(122, 79, 222));
        TopBar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TopBar2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Acropolis Institute Of Technology And Research");
        TopBar2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 550, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aitr.png"))); // NOI18N
        TopBar2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        QueryC.add(TopBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 130));

        BG.add(QueryC, "card3");

        UpdateC.setBackground(new java.awt.Color(255, 255, 255));
        UpdateC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial No", "Faculty Name", "Caption", "Description", "Post Date"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        UpdateC.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 800, 270));

        BG.add(UpdateC, "card4");

        SettingC.setBackground(new java.awt.Color(255, 255, 255));
        SettingC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(53, 33, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 50));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Email Us");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, -1));

        SettingC.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 120, 110));

        jPanel3.setBackground(new java.awt.Color(53, 33, 89));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 50));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Logout");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, -1));

        SettingC.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 120, 110));

        jPanel8.setBackground(new java.awt.Color(53, 33, 89));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password.png"))); // NOI18N
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 50));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Reset");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Password");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 120, -1));

        SettingC.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 120, 110));

        BG.add(SettingC, "card5");

        NewQueryC.setBackground(new java.awt.Color(255, 255, 255));
        NewQueryC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackNewQuery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        BackNewQuery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackNewQueryMouseClicked(evt);
            }
        });
        NewQueryC.add(BackNewQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Student2.setBackground(new java.awt.Color(255, 255, 255));
        Student2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Student2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentT2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        StudentT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentT2.setText("Add New Query");
        StudentT2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Student2.add(StudentT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 60));

        AddNeQuery.setBackground(new java.awt.Color(64, 43, 100));
        AddNeQuery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddNeQueryMouseClicked(evt);
            }
        });
        AddNeQuery.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignInBtnTxt2.setBackground(new java.awt.Color(255, 255, 255));
        SignInBtnTxt2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        SignInBtnTxt2.setForeground(new java.awt.Color(255, 255, 255));
        SignInBtnTxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignInBtnTxt2.setText("Add Query");
        AddNeQuery.add(SignInBtnTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 180, 40));

        Student2.add(AddNeQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 280, 40));

        StuID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuID.setText("To Date");
        Student2.add(StuID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 90, 40));

        StuPW.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuPW.setText("Faculty Name");
        Student2.add(StuPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 110, 40));

        FaName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        FaName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaNameActionPerformed(evt);
            }
        });
        Student2.add(FaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 300, 40));

        StuID1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuID1.setText("Query");
        Student2.add(StuID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, 40));

        NQuery.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        NQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NQueryActionPerformed(evt);
            }
        });
        Student2.add(NQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 300, 40));

        StuID2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuID2.setText("From Date");
        Student2.add(StuID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 90, 40));
        Student2.add(jDatePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 300, 30));
        Student2.add(jDatePicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 300, -1));

        NewQueryC.add(Student2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 540, 540));

        BG.add(NewQueryC, "card7");

        InboxC.setBackground(new java.awt.Color(255, 255, 255));
        InboxC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackInbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        BackInbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackInboxMouseClicked(evt);
            }
        });
        InboxC.add(BackInbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(53, 33, 89));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh.png"))); // NOI18N
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Refresh");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 80, -1));

        InboxC.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 80, 80));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Faculty  Name", "Query", "Request Date", "To Date", "From Date", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        InboxC.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 790, 350));

        BG.add(InboxC, "card6");

        PasswordResetC.setBackground(new java.awt.Color(255, 255, 255));
        PasswordResetC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackPasswordReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        BackPasswordReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackPasswordResetMouseClicked(evt);
            }
        });
        PasswordResetC.add(BackPasswordReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        inbox1.setBackground(new java.awt.Color(255, 255, 255));
        inbox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        inbox1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inboxT1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        inboxT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inboxT1.setText("PasswordReset");
        inboxT1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        inbox1.add(inboxT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 60));

        Inboxbtn1.setBackground(new java.awt.Color(64, 43, 100));
        Inboxbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inboxbtn1MouseClicked(evt);
            }
        });
        Inboxbtn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inboxBtnTxt2.setBackground(new java.awt.Color(255, 255, 255));
        inboxBtnTxt2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        inboxBtnTxt2.setForeground(new java.awt.Color(255, 255, 255));
        inboxBtnTxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inboxBtnTxt2.setText("Submit");
        Inboxbtn1.add(inboxBtnTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2, 180, 40));

        inbox1.add(Inboxbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 280, 40));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel15.setText("Confirm New");
        inbox1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 130, 40));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel12.setText("Password");
        inbox1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 130, 40));
        inbox1.add(CNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 240, 40));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel13.setText("Old Password");
        inbox1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 40));
        inbox1.add(oldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 240, 40));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel14.setText("New Password");
        inbox1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 140, 40));
        inbox1.add(newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 240, 40));
        inbox1.add(InvalidPWD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 240, 20));
        inbox1.add(InvalidPWD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 240, 20));

        PasswordResetC.add(inbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 450, 500));

        BG.add(PasswordResetC, "card8");

        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 900, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        cl.show(BG, "card2");
        Home.setBackground(new Color(85,65,118));
        Query.setBackground(new Color(64,43,100));
        Update.setBackground(new Color(64,43,100));
        Settings.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_HomeMouseClicked

    private void QueryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QueryMouseClicked
        cl.show(BG, "card3");
        Home.setBackground(new Color(64,43,100));
        Query.setBackground(new Color(85,65,118));
        Update.setBackground(new Color(64,43,100));
        Settings.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_QueryMouseClicked

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        cl.show(BG, "card4");
        this.showNewsData();
        Home.setBackground(new Color(64,43,100));
        Query.setBackground(new Color(64,43,100));
        Update.setBackground(new Color(85,65,118));
        Settings.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_UpdateMouseClicked

    private void SettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseClicked
        cl.show(BG, "card5");
        Home.setBackground(new Color(64,43,100));
        Query.setBackground(new Color(64,43,100));
        Update.setBackground(new Color(64,43,100));
        Settings.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_SettingsMouseClicked
    private void showData()
    {
        SessionFactory sf=new Configuration().configure().buildSessionFactory();
        Session session=sf.openSession();
        Transaction tx=session.beginTransaction();
        Criteria crit = session.createCriteria(QueryTable.class);
        crit.add(Restrictions.eq("stuName",SignIn.id));
        List<QueryTable> data=crit.list();
        DefaultTableModel dtm= (DefaultTableModel)jTable2.getModel();
        dtm.setRowCount(0);
        for(QueryTable st:data)
        {
            Object obj[]={st.getFaName(),st.getQuery(),st.getRequestDate(),st.getTo(),st.getFrom()};
            dtm.addRow(obj);
        }
    }
    
    private void showNewsData()
    {
        SessionFactory sf=new Configuration().configure().buildSessionFactory();
        Session session=sf.openSession();
        Transaction tx=session.beginTransaction();
        Criteria crit = session.createCriteria(NewsTable.class);
        //crit.add(Restrictions.eq("stuName",SignIn.id));
        List<NewsTable> data=crit.list();
        DefaultTableModel dtm= (DefaultTableModel)jTable3.getModel();
        dtm.setRowCount(0);
        for(NewsTable st:data)
        {
            Object obj[]={st.getSerialNo(),st.getName(),st.getCaption(),st.getDescription(),st.getPostDate()};
            dtm.addRow(obj);
        }
    }
    private void InboxbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InboxbtnMouseClicked
       cl.show(BG, "card6");
       this.showData();
    }//GEN-LAST:event_InboxbtnMouseClicked

    private void NewQueryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewQueryBtnMouseClicked
        cl.show(BG, "card7");
    }//GEN-LAST:event_NewQueryBtnMouseClicked

    private void BackInboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackInboxMouseClicked
        cl.show(BG, "card3");
    }//GEN-LAST:event_BackInboxMouseClicked

    private void BackNewQueryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackNewQueryMouseClicked
        cl.show(BG, "card3");
    }//GEN-LAST:event_BackNewQueryMouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        new SignIn().setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void AddNeQueryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNeQueryMouseClicked
        String FName = FaName.getText();
        String query = NQuery.getText();
        //String fDate = FromDate.getText();
        //String toDate = ToDate.getText();
        Date date = new Date();
        DateFormat df = DateFormat.getDateInstance(DateFormat.SHORT);
        SimpleDateFormat sdf = new SimpleDateFormat("dd:mm:yyyy");
        String da = df.format(date);
        String stuName = SignIn.id;
        String status = "not processed";
        DateModel dm=jDatePicker1.getModel();
        String fDate = dm.getDay()+" "+dm.getMonth()+" "+dm.getYear();
        dm = jDatePicker2.getModel();
        String toDate = dm.getDay()+" "+dm.getMonth()+" "+dm.getYear();
        
        SessionFactory sf=new Configuration().configure().buildSessionFactory();
        Session session = sf.openSession();
        Transaction  tx = session.beginTransaction();
        QueryTable qt = new QueryTable(stuName,FName,query,da,toDate,fDate,status);
        session.save(qt);
        tx.commit();
        session.close();
        JOptionPane.showMessageDialog(this,"submitted!!!!!");    
    }//GEN-LAST:event_AddNeQueryMouseClicked

    private void FaNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FaNameActionPerformed

    private void NQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NQueryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NQueryActionPerformed

    private void BackPasswordResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackPasswordResetMouseClicked
        cl.show(BG, "card5");
    }//GEN-LAST:event_BackPasswordResetMouseClicked

    private void Inboxbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inboxbtn1MouseClicked
        String oldPass = new String(oldPassword.getPassword());
        String newPass = new String(newPassword.getPassword());
        String CNewPass = new String(CNewPassword.getPassword());
        String id = SignIn.id;
        
        SessionFactory sf=new Configuration().configure().buildSessionFactory();
        Session session = sf.openSession();
        Transaction  tx = session.beginTransaction();
        Criteria crit=session.createCriteria(StudentTable.class);
        crit.add(Restrictions.and(Restrictions.eq("stuID",id),Restrictions.eq("stuPassword",oldPass)));
        List<StudentTable> result=crit.list();
        if(result.isEmpty())
        {
            InvalidPWD.setForeground(Color.red);
            InvalidPWD.setText("*Invalid Password");
        }
        else
        {
            if(newPass.equals(CNewPass))
            {
                StudentTable st=(StudentTable)session.get(StudentTable.class,id);
                st.setStuPassword(newPass);
                session.update(st);
                tx.commit();
                JOptionPane.showMessageDialog(this,"Password changed successfully...");
                new SignIn().setVisible(true);
                dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"New Password and Confirm New Password Does Not Match");
                InvalidPWD1.setForeground(Color.red);
                InvalidPWD1.setText("*Password Coes not match new password");
            }
        }
    }//GEN-LAST:event_Inboxbtn1MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        cl.show(BG, "card8");
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        this.showData();
    }//GEN-LAST:event_jPanel4MouseClicked
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddNeQuery;
    private javax.swing.JPanel BG;
    private javax.swing.JLabel BackInbox;
    private javax.swing.JLabel BackNewQuery;
    private javax.swing.JLabel BackPasswordReset;
    private javax.swing.JPasswordField CNewPassword;
    private javax.swing.JTextField FaName;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel HomeC;
    private javax.swing.JPanel InboxC;
    private javax.swing.JPanel Inboxbtn;
    private javax.swing.JPanel Inboxbtn1;
    private javax.swing.JLabel InvalidPWD;
    private javax.swing.JLabel InvalidPWD1;
    private javax.swing.JLabel LOGO;
    private javax.swing.JPanel LeftSide;
    private javax.swing.JTextField NQuery;
    private javax.swing.JPanel NewQueryBtn;
    private javax.swing.JPanel NewQueryC;
    private javax.swing.JPanel PasswordResetC;
    private javax.swing.JPanel Query;
    private javax.swing.JPanel QueryC;
    private javax.swing.JPanel SettingC;
    private javax.swing.JPanel Settings;
    private javax.swing.JLabel SignInBtnTxt2;
    private javax.swing.JLabel StuID;
    private javax.swing.JLabel StuID1;
    private javax.swing.JLabel StuID2;
    private javax.swing.JLabel StuPW;
    private javax.swing.JPanel Student2;
    private javax.swing.JLabel StudentT2;
    private javax.swing.JPanel TopBar;
    private javax.swing.JPanel TopBar2;
    private javax.swing.JPanel Update;
    private javax.swing.JPanel UpdateC;
    private javax.swing.JLabel contactD;
    private javax.swing.JLabel contactD1;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JLabel homeLabel1;
    private javax.swing.JLabel homeLabel2;
    private javax.swing.JLabel homeLabel3;
    private javax.swing.JPanel inbox;
    private javax.swing.JPanel inbox1;
    private javax.swing.JLabel inboxBtnTxt;
    private javax.swing.JLabel inboxBtnTxt1;
    private javax.swing.JLabel inboxBtnTxt2;
    private javax.swing.JLabel inboxT;
    private javax.swing.JLabel inboxT1;
    private javax.swing.JLabel inboxicon;
    private org.jdatepicker.JDatePicker jDatePicker1;
    private org.jdatepicker.JDatePicker jDatePicker2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JPanel newQuery;
    private javax.swing.JPasswordField oldPassword;
    private javax.swing.JLabel queryIcon;
    private javax.swing.JLabel queryLabel;
    private javax.swing.JLabel queryT;
    private javax.swing.JLabel settingLabel;
    private javax.swing.JLabel updateLabel;
    // End of variables declaration//GEN-END:variables
}
