
import hib.dto.FacultyTable;
import hib.dto.NewsTable;
import hib.dto.OperatorTable;
import hib.dto.StudentTable;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.hibernate.criterion.Restrictions;
import org.jdatepicker.DateModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Achint Rawal
 */
public class HomePageOperator extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    CardLayout cl;
    public HomePageOperator() 
    {
        initComponents();
        cl = (CardLayout)BG.getLayout();
        Home.setBackground(new Color(85,65,118));
        homeLabel3.setText("Welcome, "+SignIn.id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomeC = new javax.swing.JPanel();
        TopBar = new javax.swing.JPanel();
        homeLabel1 = new javax.swing.JLabel();
        homeLabel3 = new javax.swing.JLabel();
        homeLabel2 = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        contactD = new javax.swing.JLabel();
        contactD1 = new javax.swing.JLabel();
        LeftSide = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        Settings = new javax.swing.JPanel();
        settingLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CreateAccount = new javax.swing.JPanel();
        queryLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Update = new javax.swing.JPanel();
        updateLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BG = new javax.swing.JPanel();
        HomeC1 = new javax.swing.JPanel();
        homeLabel6 = new javax.swing.JLabel();
        homeLabel7 = new javax.swing.JLabel();
        TopBar3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        CreateAccountC = new javax.swing.JPanel();
        inbox = new javax.swing.JPanel();
        inboxT = new javax.swing.JLabel();
        inboxicon = new javax.swing.JLabel();
        CreateStuAccBtn = new javax.swing.JPanel();
        inboxBtnTxt = new javax.swing.JLabel();
        newQuery = new javax.swing.JPanel();
        queryT = new javax.swing.JLabel();
        queryIcon = new javax.swing.JLabel();
        CreateFaAccBtn = new javax.swing.JPanel();
        inboxBtnTxt1 = new javax.swing.JLabel();
        TopBar4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        UpdateC = new javax.swing.JPanel();
        BackNewQuery1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        FaAccountC = new javax.swing.JPanel();
        BackNewQuery = new javax.swing.JLabel();
        Student2 = new javax.swing.JPanel();
        StudentT2 = new javax.swing.JLabel();
        CreateFaAcc = new javax.swing.JPanel();
        SignInBtnTxt2 = new javax.swing.JLabel();
        StuID = new javax.swing.JLabel();
        StuPW = new javax.swing.JLabel();
        FaName = new javax.swing.JTextField();
        StuID1 = new javax.swing.JLabel();
        Dept = new javax.swing.JTextField();
        StuID2 = new javax.swing.JLabel();
        Sub = new javax.swing.JTextField();
        StuID3 = new javax.swing.JLabel();
        Contact = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        EmailId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Address = new javax.swing.JTextArea();
        StuID5 = new javax.swing.JLabel();
        dob = new org.jdatepicker.JDatePicker();
        FaId = new javax.swing.JTextField();
        StuPW3 = new javax.swing.JLabel();
        StuAccC = new javax.swing.JPanel();
        BackInbox = new javax.swing.JLabel();
        Student3 = new javax.swing.JPanel();
        StudentT3 = new javax.swing.JLabel();
        CreateStuAcc = new javax.swing.JPanel();
        SignInBtnTxt3 = new javax.swing.JLabel();
        StuID4 = new javax.swing.JLabel();
        StuPW1 = new javax.swing.JLabel();
        FaName1 = new javax.swing.JTextField();
        StuID6 = new javax.swing.JLabel();
        Dept1 = new javax.swing.JTextField();
        StuID7 = new javax.swing.JLabel();
        Sub1 = new javax.swing.JTextField();
        StuID8 = new javax.swing.JLabel();
        Contact1 = new javax.swing.JTextField();
        Email1 = new javax.swing.JLabel();
        EmailId1 = new javax.swing.JTextField();
        StuID9 = new javax.swing.JLabel();
        dob1 = new org.jdatepicker.JDatePicker();
        EmailId2 = new javax.swing.JTextField();
        stuId = new javax.swing.JTextField();
        StuID11 = new javax.swing.JLabel();
        PasswordResetC = new javax.swing.JPanel();
        inbox1 = new javax.swing.JPanel();
        inboxT1 = new javax.swing.JLabel();
        Inboxbtn1 = new javax.swing.JPanel();
        inboxBtnTxt2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        CNewPassword = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        oldPassword = new javax.swing.JPasswordField();
        jLabel21 = new javax.swing.JLabel();
        newPassword = new javax.swing.JPasswordField();
        InvalidPWD = new javax.swing.JLabel();
        InvalidPWD1 = new javax.swing.JLabel();
        BackInbox1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Student4 = new javax.swing.JPanel();
        StudentT4 = new javax.swing.JLabel();
        AddNeQuery = new javax.swing.JPanel();
        SignInBtnTxt4 = new javax.swing.JLabel();
        StuPW2 = new javax.swing.JLabel();
        FaName2 = new javax.swing.JTextField();
        StuID10 = new javax.swing.JLabel();
        NQuery = new javax.swing.JTextField();
        SettingC = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        HomeC.setBackground(new java.awt.Color(255, 255, 255));
        HomeC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopBar.setBackground(new java.awt.Color(122, 79, 222));
        TopBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeLabel1.setBackground(new java.awt.Color(255, 255, 255));
        homeLabel1.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        homeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel1.setText("Last Login : ");
        TopBar.add(homeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 330, 30));

        homeLabel3.setBackground(new java.awt.Color(255, 255, 255));
        homeLabel3.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        homeLabel3.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel3.setText("Welcome, ");
        TopBar.add(homeLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 210, 30));

        HomeC.add(TopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 900, 90));

        homeLabel2.setBackground(new java.awt.Color(0, 0, 0));
        homeLabel2.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        homeLabel2.setText("History,");
        HomeC.add(homeLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 210, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Footer.setBackground(new java.awt.Color(122, 79, 222));
        Footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contactD.setBackground(new java.awt.Color(255, 255, 255));
        contactD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        contactD.setForeground(new java.awt.Color(255, 255, 255));
        contactD.setText("Contact Number : +91 1234567890");
        Footer.add(contactD, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 290, 30));

        contactD1.setBackground(new java.awt.Color(255, 255, 255));
        contactD1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        contactD1.setForeground(new java.awt.Color(255, 255, 255));
        contactD1.setText("Email Id : lecturebackup@collegename.in");
        Footer.add(contactD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 330, 30));

        getContentPane().add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1210, 50));

        LeftSide.setBackground(new java.awt.Color(53, 33, 89));
        LeftSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGO.setBackground(new java.awt.Color(255, 255, 255));
        LOGO.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LOGO.setForeground(new java.awt.Color(255, 255, 255));
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo1.png"))); // NOI18N
        LeftSide.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 180, 100));

        Settings.setBackground(new java.awt.Color(64, 43, 100));
        Settings.setPreferredSize(new java.awt.Dimension(500, 300));
        Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsMouseClicked(evt);
            }
        });
        Settings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settingLabel.setBackground(new java.awt.Color(255, 255, 255));
        settingLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        settingLabel.setForeground(new java.awt.Color(255, 255, 255));
        settingLabel.setText("Settings");
        Settings.add(settingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings.png"))); // NOI18N
        Settings.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 50));

        LeftSide.add(Settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 310, 50));

        Home.setBackground(new java.awt.Color(64, 43, 100));
        Home.setPreferredSize(new java.awt.Dimension(500, 300));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeLabel.setBackground(new java.awt.Color(255, 255, 255));
        homeLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel.setText(" Home");
        Home.add(homeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 210, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        Home.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 50));

        LeftSide.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 310, 50));

        CreateAccount.setBackground(new java.awt.Color(64, 43, 100));
        CreateAccount.setPreferredSize(new java.awt.Dimension(500, 300));
        CreateAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateAccountMouseClicked(evt);
            }
        });
        CreateAccount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        queryLabel.setBackground(new java.awt.Color(255, 255, 255));
        queryLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        queryLabel.setForeground(new java.awt.Color(255, 255, 255));
        queryLabel.setText("Create Account");
        CreateAccount.add(queryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 210, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/query.png"))); // NOI18N
        CreateAccount.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 50));

        LeftSide.add(CreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 310, 50));

        Update.setBackground(new java.awt.Color(64, 43, 100));
        Update.setPreferredSize(new java.awt.Dimension(500, 300));
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
        });
        Update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateLabel.setBackground(new java.awt.Color(255, 255, 255));
        updateLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        updateLabel.setForeground(new java.awt.Color(255, 255, 255));
        updateLabel.setText("Updates");
        Update.add(updateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 210, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        Update.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 50));

        LeftSide.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 310, 50));

        getContentPane().add(LeftSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 640));

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setLayout(new java.awt.CardLayout());

        HomeC1.setBackground(new java.awt.Color(255, 255, 255));
        HomeC1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeLabel6.setBackground(new java.awt.Color(255, 255, 255));
        homeLabel6.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        homeLabel6.setText("Welcome, ");
        HomeC1.add(homeLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 210, 30));

        homeLabel7.setBackground(new java.awt.Color(255, 255, 255));
        homeLabel7.setFont(new java.awt.Font("Arial", 0, 21)); // NOI18N
        homeLabel7.setText("LoginTime : ");
        HomeC1.add(homeLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 330, 30));

        TopBar3.setBackground(new java.awt.Color(122, 79, 222));
        TopBar3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TopBar3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel27.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Acropolis Institute Of Technology And Research");
        TopBar3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 550, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aitr.png"))); // NOI18N
        TopBar3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        HomeC1.add(TopBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 130));

        BG.add(HomeC1, "card10");

        CreateAccountC.setBackground(new java.awt.Color(255, 255, 255));
        CreateAccountC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inbox.setBackground(new java.awt.Color(255, 255, 255));
        inbox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        inbox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inboxT.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        inboxT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inboxT.setText("Create Student Account");
        inboxT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        inbox.add(inboxT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 60));

        inboxicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inboxicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inbox1.png"))); // NOI18N
        inboxicon.setToolTipText("");
        inbox.add(inboxicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 320, 60));

        CreateStuAccBtn.setBackground(new java.awt.Color(64, 43, 100));
        CreateStuAccBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateStuAccBtnMouseClicked(evt);
            }
        });
        CreateStuAccBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inboxBtnTxt.setBackground(new java.awt.Color(255, 255, 255));
        inboxBtnTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        inboxBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        inboxBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inboxBtnTxt.setText("Create Accounnt");
        CreateStuAccBtn.add(inboxBtnTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2, 180, 40));

        inbox.add(CreateStuAccBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 280, 40));

        CreateAccountC.add(inbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 320, 400));

        newQuery.setBackground(new java.awt.Color(255, 255, 255));
        newQuery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        newQuery.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        queryT.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        queryT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        queryT.setText("Create Faculty Account");
        queryT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        newQuery.add(queryT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 60));

        queryIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        queryIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newQuery1_1.png"))); // NOI18N
        queryIcon.setToolTipText("");
        newQuery.add(queryIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 320, 70));

        CreateFaAccBtn.setBackground(new java.awt.Color(64, 43, 100));
        CreateFaAccBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateFaAccBtnMouseClicked(evt);
            }
        });
        CreateFaAccBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inboxBtnTxt1.setBackground(new java.awt.Color(255, 255, 255));
        inboxBtnTxt1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        inboxBtnTxt1.setForeground(new java.awt.Color(255, 255, 255));
        inboxBtnTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inboxBtnTxt1.setText("Create Account");
        CreateFaAccBtn.add(inboxBtnTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2, 180, 40));

        newQuery.add(CreateFaAccBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 280, 40));

        CreateAccountC.add(newQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 320, 400));

        TopBar4.setBackground(new java.awt.Color(122, 79, 222));
        TopBar4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TopBar4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel30.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Acropolis Institute Of Technology And Research");
        TopBar4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 550, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aitr.png"))); // NOI18N
        TopBar4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        CreateAccountC.add(TopBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 130));

        BG.add(CreateAccountC, "card3");

        UpdateC.setBackground(new java.awt.Color(255, 255, 255));
        UpdateC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackNewQuery1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newQuery1_1.png"))); // NOI18N
        BackNewQuery1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackNewQuery1MouseClicked(evt);
            }
        });
        UpdateC.add(BackNewQuery1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial No", "Faculty Name", "Caption", "Description", "Post Date"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        UpdateC.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 800, 330));

        BG.add(UpdateC, "card4");

        FaAccountC.setBackground(new java.awt.Color(255, 255, 255));
        FaAccountC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackNewQuery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        BackNewQuery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackNewQueryMouseClicked(evt);
            }
        });
        FaAccountC.add(BackNewQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Student2.setBackground(new java.awt.Color(255, 255, 255));
        Student2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Student2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentT2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        StudentT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentT2.setText("Faculty Account Creation");
        StudentT2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Student2.add(StudentT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 60));

        CreateFaAcc.setBackground(new java.awt.Color(64, 43, 100));
        CreateFaAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateFaAccMouseClicked(evt);
            }
        });
        CreateFaAcc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignInBtnTxt2.setBackground(new java.awt.Color(255, 255, 255));
        SignInBtnTxt2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        SignInBtnTxt2.setForeground(new java.awt.Color(255, 255, 255));
        SignInBtnTxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignInBtnTxt2.setText("Submit");
        CreateFaAcc.add(SignInBtnTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 180, 40));

        Student2.add(CreateFaAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 280, 40));

        StuID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuID.setText("Date Of Birth");
        Student2.add(StuID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 140, 40));

        StuPW.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuPW.setText("Faculty ID");
        Student2.add(StuPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 40));

        FaName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        FaName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaNameActionPerformed(evt);
            }
        });
        Student2.add(FaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 300, 40));

        StuID1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuID1.setText("Department");
        Student2.add(StuID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, 40));

        Dept.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeptActionPerformed(evt);
            }
        });
        Student2.add(Dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 300, 40));

        StuID2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuID2.setText("Subject");
        Student2.add(StuID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 90, 40));

        Sub.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubActionPerformed(evt);
            }
        });
        Student2.add(Sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 300, 40));

        StuID3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuID3.setText("Contact Number");
        Student2.add(StuID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 140, 40));

        Contact.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactActionPerformed(evt);
            }
        });
        Student2.add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 300, 40));

        Email.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Email.setText("Email Id");
        Student2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 140, 40));

        EmailId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailIdActionPerformed(evt);
            }
        });
        Student2.add(EmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 300, 40));

        Address.setColumns(20);
        Address.setRows(5);
        jScrollPane1.setViewportView(Address);

        Student2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 300, 80));

        StuID5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuID5.setText("Address");
        Student2.add(StuID5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 140, 40));
        Student2.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 300, 30));

        FaId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        FaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaIdActionPerformed(evt);
            }
        });
        Student2.add(FaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 300, 40));

        StuPW3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuPW3.setText("Faculty Name");
        Student2.add(StuPW3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 40));

        FaAccountC.add(Student2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 540, 600));

        BG.add(FaAccountC, "card7");

        StuAccC.setBackground(new java.awt.Color(255, 255, 255));
        StuAccC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackInbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        BackInbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackInboxMouseClicked(evt);
            }
        });
        StuAccC.add(BackInbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Student3.setBackground(new java.awt.Color(255, 255, 255));
        Student3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Student3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentT3.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        StudentT3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentT3.setText("Student Account Creation");
        StudentT3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Student3.add(StudentT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 60));

        CreateStuAcc.setBackground(new java.awt.Color(64, 43, 100));
        CreateStuAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateStuAccMouseClicked(evt);
            }
        });
        CreateStuAcc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignInBtnTxt3.setBackground(new java.awt.Color(255, 255, 255));
        SignInBtnTxt3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        SignInBtnTxt3.setForeground(new java.awt.Color(255, 255, 255));
        SignInBtnTxt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignInBtnTxt3.setText("Submit");
        CreateStuAcc.add(SignInBtnTxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 180, 40));

        Student3.add(CreateStuAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 280, 40));

        StuID4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuID4.setText("Date Of Birth");
        Student3.add(StuID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 140, 40));

        StuPW1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuPW1.setText("Student Name");
        Student3.add(StuPW1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 40));

        FaName1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        FaName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaName1ActionPerformed(evt);
            }
        });
        Student3.add(FaName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 300, 40));

        StuID6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuID6.setText("Student Id");
        Student3.add(StuID6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 40));

        Dept1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Dept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dept1ActionPerformed(evt);
            }
        });
        Student3.add(Dept1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 300, 40));

        StuID7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuID7.setText("Subject");
        Student3.add(StuID7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 90, 40));

        Sub1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub1ActionPerformed(evt);
            }
        });
        Student3.add(Sub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 300, 40));

        StuID8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuID8.setText("Section");
        Student3.add(StuID8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, 40));

        Contact1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Contact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contact1ActionPerformed(evt);
            }
        });
        Student3.add(Contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 300, 40));

        Email1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Email1.setText("Year");
        Student3.add(Email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 140, 40));

        EmailId1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EmailId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailId1ActionPerformed(evt);
            }
        });
        Student3.add(EmailId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 300, 40));

        StuID9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuID9.setText("Contact No.");
        Student3.add(StuID9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 140, 40));
        Student3.add(dob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 300, 30));

        EmailId2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EmailId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailId2ActionPerformed(evt);
            }
        });
        Student3.add(EmailId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 300, 40));

        stuId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        stuId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuIdActionPerformed(evt);
            }
        });
        Student3.add(stuId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 300, 40));

        StuID11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuID11.setText("Department");
        Student3.add(StuID11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, 40));

        StuAccC.add(Student3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 540, 610));

        BG.add(StuAccC, "card6");

        PasswordResetC.setBackground(new java.awt.Color(255, 255, 255));
        PasswordResetC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inbox1.setBackground(new java.awt.Color(255, 255, 255));
        inbox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        inbox1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inboxT1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        inboxT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inboxT1.setText("PasswordReset");
        inboxT1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        inbox1.add(inboxT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 60));

        Inboxbtn1.setBackground(new java.awt.Color(64, 43, 100));
        Inboxbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inboxbtn1MouseClicked(evt);
            }
        });
        Inboxbtn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inboxBtnTxt2.setBackground(new java.awt.Color(255, 255, 255));
        inboxBtnTxt2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        inboxBtnTxt2.setForeground(new java.awt.Color(255, 255, 255));
        inboxBtnTxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inboxBtnTxt2.setText("Submit");
        Inboxbtn1.add(inboxBtnTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2, 180, 40));

        inbox1.add(Inboxbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 280, 40));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel16.setText("Confirm New");
        inbox1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 130, 40));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel19.setText("Password");
        inbox1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 130, 40));
        inbox1.add(CNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 240, 40));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel20.setText("Old Password");
        inbox1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 40));
        inbox1.add(oldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 240, 40));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel21.setText("New Password");
        inbox1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 140, 40));
        inbox1.add(newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 240, 40));
        inbox1.add(InvalidPWD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 240, 20));
        inbox1.add(InvalidPWD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 240, 20));

        PasswordResetC.add(inbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 450, 500));

        BackInbox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        BackInbox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackInbox1MouseClicked(evt);
            }
        });
        PasswordResetC.add(BackInbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        BG.add(PasswordResetC, "card8");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Student4.setBackground(new java.awt.Color(255, 255, 255));
        Student4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Student4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentT4.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        StudentT4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentT4.setText("Insert News");
        StudentT4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Student4.add(StudentT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 60));

        AddNeQuery.setBackground(new java.awt.Color(64, 43, 100));
        AddNeQuery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddNeQueryMouseClicked(evt);
            }
        });
        AddNeQuery.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignInBtnTxt4.setBackground(new java.awt.Color(255, 255, 255));
        SignInBtnTxt4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        SignInBtnTxt4.setForeground(new java.awt.Color(255, 255, 255));
        SignInBtnTxt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignInBtnTxt4.setText("Post news");
        AddNeQuery.add(SignInBtnTxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 180, 40));

        Student4.add(AddNeQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 280, 40));

        StuPW2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuPW2.setText("Caption");
        Student4.add(StuPW2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 110, 40));

        FaName2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        FaName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaName2ActionPerformed(evt);
            }
        });
        Student4.add(FaName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 300, 40));

        StuID10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        StuID10.setText("Description");
        Student4.add(StuID10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 90, 40));

        NQuery.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        NQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NQueryActionPerformed(evt);
            }
        });
        Student4.add(NQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 300, 40));

        jPanel1.add(Student4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 540, 420));

        BG.add(jPanel1, "card100");

        SettingC.setBackground(new java.awt.Color(255, 255, 255));
        SettingC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(53, 33, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 50));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Email Us");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, -1));

        SettingC.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 120, 110));

        jPanel3.setBackground(new java.awt.Color(53, 33, 89));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 50));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Logout");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, -1));

        SettingC.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 120, 110));

        jPanel8.setBackground(new java.awt.Color(53, 33, 89));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password.png"))); // NOI18N
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 50));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Reset");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Password");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 120, -1));

        SettingC.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 120, 110));

        jPanel4.setBackground(new java.awt.Color(53, 33, 89));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete.png"))); // NOI18N
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 50));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Account");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Delete");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 120, -1));

        SettingC.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 120, 110));

        jPanel5.setBackground(new java.awt.Color(53, 33, 89));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 50));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Details");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Update");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 120, -1));

        SettingC.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 120, 110));

        BG.add(SettingC, "card9");

        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 900, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        cl.show(BG, "card10");
        Home.setBackground(new Color(85,65,118));
        CreateAccount.setBackground(new Color(64,43,100));
        Update.setBackground(new Color(64,43,100));
        Settings.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_HomeMouseClicked

    private void CreateAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAccountMouseClicked
        cl.show(BG, "card3");
        Home.setBackground(new Color(64,43,100));
        CreateAccount.setBackground(new Color(85,65,118));
        Update.setBackground(new Color(64,43,100));
        Settings.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_CreateAccountMouseClicked

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        cl.show(BG, "card4");
        this.showNewsData();
        Home.setBackground(new Color(64,43,100));
        CreateAccount.setBackground(new Color(64,43,100));
        Update.setBackground(new Color(85,65,118));
        Settings.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_UpdateMouseClicked

    private void SettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseClicked
        cl.show(BG, "card5");
        Home.setBackground(new Color(64,43,100));
        CreateAccount.setBackground(new Color(64,43,100));
        Update.setBackground(new Color(64,43,100));
        Settings.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_SettingsMouseClicked

    private void CreateStuAccBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateStuAccBtnMouseClicked
        cl.show(BG, "card6");
    }//GEN-LAST:event_CreateStuAccBtnMouseClicked

    private void CreateFaAccBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateFaAccBtnMouseClicked
        cl.show(BG, "card7");
    }//GEN-LAST:event_CreateFaAccBtnMouseClicked

    private void BackInboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackInboxMouseClicked
        cl.show(BG, "card3");
    }//GEN-LAST:event_BackInboxMouseClicked

    private void BackNewQueryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackNewQueryMouseClicked
        cl.show(BG, "card3");
    }//GEN-LAST:event_BackNewQueryMouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        new SignIn().setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void CreateFaAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateFaAccMouseClicked
        String FName = FaName.getText();
        String FaIdd = FaId.getText();
        String Password = "ABC123";
        String dept = Dept.getText();
        String sub = Sub.getText();
        String contact = Contact.getText();
        String emailId = EmailId.getText();
        String address = Address.getText();
        String dOB;
        DateModel dm = dob.getModel();
        dOB=dm.getDay()+" "+dm.getMonth()+" "+dm.getYear();
        SessionFactory sf=new Configuration().configure().buildSessionFactory();
        Session session = sf.openSession();
        Transaction  tx = session.beginTransaction();
        FacultyTable ft = new FacultyTable(FName,FaIdd,Password,dept,sub,contact,emailId,address,dOB);
        session.save(ft);
        tx.commit();
        session.close();
        JOptionPane.showMessageDialog(this,"submitted!!!!!");    
    }//GEN-LAST:event_CreateFaAccMouseClicked

    private void FaNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FaNameActionPerformed

    private void DeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeptActionPerformed

    private void SubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubActionPerformed

    private void ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactActionPerformed

    private void EmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailIdActionPerformed

    private void CreateStuAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateStuAccMouseClicked
        String FName = FaName1.getText();
        String FaId = stuId.getText();
        String Password = "ABC123";
        String dept = Dept1.getText();
        String sub = Sub1.getText();
        String contact = Contact1.getText();
        String year = EmailId2.getText();
        String contactNo = EmailId1.getText();
        DateModel dm = dob.getModel();
        String dOB=dm.getDay()+" "+dm.getMonth()+" "+dm.getYear();
        
        SessionFactory sf=new Configuration().configure().buildSessionFactory();
        Session session = sf.openSession();
        Transaction  tx = session.beginTransaction();
        StudentTable ft = new StudentTable(FaId,FName,Password,dOB,dept,sub,year,contactNo);
        session.save(ft);
        tx.commit();
        session.close();
        JOptionPane.showMessageDialog(this,"submitted Student!!!!!");
    }//GEN-LAST:event_CreateStuAccMouseClicked

    private void FaName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FaName1ActionPerformed

    private void Dept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dept1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dept1ActionPerformed

    private void Sub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub1ActionPerformed

    private void Contact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Contact1ActionPerformed

    private void EmailId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailId1ActionPerformed

    private void EmailId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailId2ActionPerformed

    private void BackNewQuery1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackNewQuery1MouseClicked
        cl.show(BG, "card100");
    }//GEN-LAST:event_BackNewQuery1MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        cl.show(BG, "card9");
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void Inboxbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inboxbtn1MouseClicked
        String oldPass = new String(oldPassword.getPassword());
        String newPass = new String(newPassword.getPassword());
        String CNewPass = new String(CNewPassword.getPassword());
        String id = SignIn.id;

        SessionFactory sf=new Configuration().configure().buildSessionFactory();
        Session session = sf.openSession();
        Transaction  tx = session.beginTransaction();
        Criteria crit=session.createCriteria(OperatorTable.class);
        crit.add(Restrictions.and(Restrictions.eq("opID",id),Restrictions.eq("opPassword",oldPass)));
        List<OperatorTable> result=crit.list();
        if(result.isEmpty())
        {
            InvalidPWD.setForeground(Color.red);
            InvalidPWD.setText("*Invalid Password");
        }
        else
        {
            if(newPass.equals(CNewPass))
            {
                OperatorTable st=(OperatorTable)session.get(OperatorTable.class,id);
                st.setOpPassword(newPass);
                session.update(st);
                tx.commit();
                JOptionPane.showMessageDialog(this,"Password changed successfully...");
                new SignIn().setVisible(true);
                dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"New Password and Confirm New Password Does Not Match");
                InvalidPWD1.setForeground(Color.red);
                InvalidPWD1.setText("*Password Coes not match new password");
            }
        }
    }//GEN-LAST:event_Inboxbtn1MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        cl.show(BG, "card8");
    }//GEN-LAST:event_jPanel8MouseClicked

    private void BackInbox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackInbox1MouseClicked
        cl.show(BG, "card5");
    }//GEN-LAST:event_BackInbox1MouseClicked

    private void AddNeQueryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNeQueryMouseClicked
        String caption = FaName.getText();
        String name = SignIn.id;
        String description = NQuery.getText();
        Date date = new Date();
        DateFormat df = DateFormat.getDateInstance(DateFormat.SHORT);
        SimpleDateFormat sdf = new SimpleDateFormat("dd:mm:yyyy");
        String da = df.format(date);
        //String fDate = FromDate.getText();
        //String toDate = ToDate.getText();

        SessionFactory sf=new Configuration().configure().buildSessionFactory();
        Session session = sf.openSession();
        Transaction  tx = session.beginTransaction();
        NewsTable qt = new NewsTable(name,caption,description,da);
        session.save(qt);
        tx.commit();
        session.close();
        JOptionPane.showMessageDialog(this,"submitted!!!!!");
        FaName.setText("");
        NQuery.setText("");
    }//GEN-LAST:event_AddNeQueryMouseClicked

    private void FaName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FaName2ActionPerformed

    private void NQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NQueryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NQueryActionPerformed

    private void FaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FaIdActionPerformed

    private void stuIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuIdActionPerformed
        
    private void showNewsData()
    {
        SessionFactory sf=new Configuration().configure().buildSessionFactory();
        Session session=sf.openSession();
        Transaction tx=session.beginTransaction();
        Criteria crit = session.createCriteria(NewsTable.class);
        //crit.add(Restrictions.eq("stuName",SignIn.id));
        List<NewsTable> data=crit.list();
        DefaultTableModel dtm= (DefaultTableModel)jTable3.getModel();
        dtm.setRowCount(0);
        for(NewsTable st:data)
        {
            Object obj[]={st.getSerialNo(),st.getName(),st.getCaption(),st.getDescription(),st.getPostDate()};
            dtm.addRow(obj);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageOperator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddNeQuery;
    private javax.swing.JTextArea Address;
    private javax.swing.JPanel BG;
    private javax.swing.JLabel BackInbox;
    private javax.swing.JLabel BackInbox1;
    private javax.swing.JLabel BackNewQuery;
    private javax.swing.JLabel BackNewQuery1;
    private javax.swing.JPasswordField CNewPassword;
    private javax.swing.JTextField Contact;
    private javax.swing.JTextField Contact1;
    private javax.swing.JPanel CreateAccount;
    private javax.swing.JPanel CreateAccountC;
    private javax.swing.JPanel CreateFaAcc;
    private javax.swing.JPanel CreateFaAccBtn;
    private javax.swing.JPanel CreateStuAcc;
    private javax.swing.JPanel CreateStuAccBtn;
    private javax.swing.JTextField Dept;
    private javax.swing.JTextField Dept1;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Email1;
    private javax.swing.JTextField EmailId;
    private javax.swing.JTextField EmailId1;
    private javax.swing.JTextField EmailId2;
    private javax.swing.JPanel FaAccountC;
    private javax.swing.JTextField FaId;
    private javax.swing.JTextField FaName;
    private javax.swing.JTextField FaName1;
    private javax.swing.JTextField FaName2;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel HomeC;
    private javax.swing.JPanel HomeC1;
    private javax.swing.JPanel Inboxbtn1;
    private javax.swing.JLabel InvalidPWD;
    private javax.swing.JLabel InvalidPWD1;
    private javax.swing.JLabel LOGO;
    private javax.swing.JPanel LeftSide;
    private javax.swing.JTextField NQuery;
    private javax.swing.JPanel PasswordResetC;
    private javax.swing.JPanel SettingC;
    private javax.swing.JPanel Settings;
    private javax.swing.JLabel SignInBtnTxt2;
    private javax.swing.JLabel SignInBtnTxt3;
    private javax.swing.JLabel SignInBtnTxt4;
    private javax.swing.JPanel StuAccC;
    private javax.swing.JLabel StuID;
    private javax.swing.JLabel StuID1;
    private javax.swing.JLabel StuID10;
    private javax.swing.JLabel StuID11;
    private javax.swing.JLabel StuID2;
    private javax.swing.JLabel StuID3;
    private javax.swing.JLabel StuID4;
    private javax.swing.JLabel StuID5;
    private javax.swing.JLabel StuID6;
    private javax.swing.JLabel StuID7;
    private javax.swing.JLabel StuID8;
    private javax.swing.JLabel StuID9;
    private javax.swing.JLabel StuPW;
    private javax.swing.JLabel StuPW1;
    private javax.swing.JLabel StuPW2;
    private javax.swing.JLabel StuPW3;
    private javax.swing.JPanel Student2;
    private javax.swing.JPanel Student3;
    private javax.swing.JPanel Student4;
    private javax.swing.JLabel StudentT2;
    private javax.swing.JLabel StudentT3;
    private javax.swing.JLabel StudentT4;
    private javax.swing.JTextField Sub;
    private javax.swing.JTextField Sub1;
    private javax.swing.JPanel TopBar;
    private javax.swing.JPanel TopBar3;
    private javax.swing.JPanel TopBar4;
    private javax.swing.JPanel Update;
    private javax.swing.JPanel UpdateC;
    private javax.swing.JLabel contactD;
    private javax.swing.JLabel contactD1;
    private org.jdatepicker.JDatePicker dob;
    private org.jdatepicker.JDatePicker dob1;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JLabel homeLabel1;
    private javax.swing.JLabel homeLabel2;
    private javax.swing.JLabel homeLabel3;
    private javax.swing.JLabel homeLabel6;
    private javax.swing.JLabel homeLabel7;
    private javax.swing.JPanel inbox;
    private javax.swing.JPanel inbox1;
    private javax.swing.JLabel inboxBtnTxt;
    private javax.swing.JLabel inboxBtnTxt1;
    private javax.swing.JLabel inboxBtnTxt2;
    private javax.swing.JLabel inboxT;
    private javax.swing.JLabel inboxT1;
    private javax.swing.JLabel inboxicon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JPanel newQuery;
    private javax.swing.JPasswordField oldPassword;
    private javax.swing.JLabel queryIcon;
    private javax.swing.JLabel queryLabel;
    private javax.swing.JLabel queryT;
    private javax.swing.JLabel settingLabel;
    private javax.swing.JTextField stuId;
    private javax.swing.JLabel updateLabel;
    // End of variables declaration//GEN-END:variables
}
