
import hib.dto.OperatorTable;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.hibernate.criterion.Restrictions;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Achint Rawal
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BGpanel = new javax.swing.JPanel();
        lecture = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        Opaque = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bgImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pwField = new javax.swing.JPasswordField();
        invalidUiD = new javax.swing.JLabel();
        invalidPWD = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BGpanel.setBackground(new java.awt.Color(255, 255, 255));
        BGpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lecture.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        lecture.setText("BACKUP");
        BGpanel.add(lecture, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 110, 50));

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel3.setText("LECTURE");
        BGpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 120, 50));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        BGpanel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 150, 130));

        Opaque.setBackground(new java.awt.Color(255, 255, 255));
        Opaque.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));
        Opaque.add(jPanel1);
        jPanel1.setBounds(0, 40, 1210, 100);

        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG.png"))); // NOI18N
        Opaque.add(bgImage);
        bgImage.setBounds(80, 330, 526, 332);

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabel2.setText("User-Id");
        Opaque.add(jLabel2);
        jLabel2.setBounds(650, 350, 100, 40);

        idField.setBackground(new java.awt.Color(204, 255, 255));
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        Opaque.add(idField);
        idField.setBounds(780, 350, 340, 40);

        jLabel4.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabel4.setText("Password");
        Opaque.add(jLabel4);
        jLabel4.setBounds(650, 440, 110, 40);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Opaque.add(jButton1);
        jButton1.setBounds(820, 540, 130, 40);

        pwField.setBackground(new java.awt.Color(204, 255, 255));
        Opaque.add(pwField);
        pwField.setBounds(780, 440, 340, 40);

        invalidUiD.setBackground(new java.awt.Color(255, 51, 51));
        Opaque.add(invalidUiD);
        invalidUiD.setBounds(780, 490, 340, 20);

        invalidPWD.setBackground(new java.awt.Color(255, 51, 51));
        Opaque.add(invalidPWD);
        invalidPWD.setBounds(780, 400, 340, 20);

        BGpanel.add(Opaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 810));

        getContentPane().add(BGpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id = idField.getText();
        char ch[] = pwField.getPassword();
        String password = new String(ch);
        
        SessionFactory sf = new Configuration().configure().buildSessionFactory();
        Session session = sf.openSession();//used to open table
        Transaction tx = session.beginTransaction();
        
        Criteria crit = session.createCriteria(OperatorTable.class);
        crit.add(Restrictions.and(Restrictions.eq("opId",id),Restrictions.eq("opPassword",password)));
        List <OperatorTable> result = crit.list();
        
        if(result.isEmpty())
        {
            invalidUiD.setForeground(Color.red);
            invalidPWD.setForeground(Color.red);
            invalidUiD.setText("*invalid User Id");
            invalidPWD.setText("*invalid Password");
            pwField.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Welcome");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BGpanel;
    private javax.swing.JPanel Opaque;
    private javax.swing.JLabel bgImage;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel invalidPWD;
    private javax.swing.JLabel invalidUiD;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lecture;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField pwField;
    // End of variables declaration//GEN-END:variables
}
