import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Achint Rawal
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */

    public SplashScreen() 
    {
        initComponents();
       setVisible(true);
       
       try
       {
           for(int i=0;i<=100;i++)
           {
               Thread.sleep(70);
               Percentage.setText(i+"%");
              
               if(i==10)
               {
                   Loading.setText("Connecting to Servers...");
               }
               if(i==30)
               {
                   Loading.setText("Loading Databases...");
               }
               if(i==50)
               {
                   Loading.setText("Connecting to Databases...");
               }
               if(i==70)
               {
                   Loading.setText("Connection Established...");
               }
               if(i==90)
               {   
                   Loading.setText("Launching Application...");
               }
               if(i==95)
               {
                   Loading.setText("Lets Go!!!!");
               }
               ProgressBar.setValue(i);
           }
           new SignIn().setVisible(true);
                dispose();
       }catch(InterruptedException ex){ }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        Background = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        Loading = new javax.swing.JLabel();
        Topic = new javax.swing.JLabel();
        Percentage = new javax.swing.JLabel();
        Gradient = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BG.setBackground(new java.awt.Color(204, 255, 255));
        BG.setPreferredSize(new java.awt.Dimension(1000, 600));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroundImg.png"))); // NOI18N
        BG.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 270, 520));
        BG.add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1000, 20));

        Loading.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Loading.setForeground(new java.awt.Color(255, 255, 255));
        Loading.setText("Loading...");
        BG.add(Loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 300, -1));

        Topic.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Topic.setForeground(new java.awt.Color(255, 255, 255));
        Topic.setText(" Lecture Backup");
        BG.add(Topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 400, 80));

        Percentage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Percentage.setForeground(new java.awt.Color(255, 255, 255));
        Percentage.setText("0%");
        BG.add(Percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 550, 40, -1));

        Gradient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gradient.png"))); // NOI18N
        Gradient.setText("jLabel1");
        BG.add(Gradient, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -7, 1000, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
            new SplashScreen();
                     

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Gradient;
    private javax.swing.JLabel Loading;
    private javax.swing.JLabel Percentage;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel Topic;
    // End of variables declaration//GEN-END:variables
}
